receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  loki:
    endpoint: http://Mustafa-loki:3100/loki/api/v1/push
    tls:
      insecure: true 


extensions:
  health_check:
  zpages:
    endpoint: otel:55679


processors:
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
