apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mustafa
  name: blazor-web-deployment
  labels:
    app: blazor-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blazor-web
  template:
    metadata:
      labels:
        app: blazor-web
    spec:
      containers:
      - name: blazor-web
        image: otel/opentelemetry-collector-contrib:0.75.0
        ports:
        - containerPort: 4317