name: Mustafa Deploying For CI-CD
on: [push]
jobs:
  MJDeplyPiP: 
    runs-on: self-hosted
    steps:
      - name: "alex-office2"
        run: |
            # rm -rf ./GrafanaOpenTelemetryPluralsight1
            git clone "https://${{secrets.CICD}}@/github.com/MJebran/GrafanaOpenTelemetryPluralsight1"
            # cd to gitub   
            cd ./GrafanaOpenTelemetryPluralsight1/MobileApp/MustafasDockerFile
            docker compose up --build -d

      - name: Integration Tests
        run: |
          cd ./ticketsrus-dusty-mustafa-ethan/MobileApp/TestsRUS/
          dotnet test
      - name: Unit Tests
        run: |
          cd ./ticketsrus-dust-mustafa-ethan/MobileApp/UnitTestsRUs/
          dotnet test


      #       # docker compose down -v 
      # - uses: actions/checkout@master
            
      # - name: Check Compose Outcome
      #   if: ${{ success() }}
      #   run: |
      #       echo "Docker Compose succeeded."
            
      # - name: letMicrosoft know Teams
      #   uses: skitionek/notify-microsoft-teams@master
      #   if: always()
      #   with:
      #       webhook_url: ${{ secrets.CICD }}