name: Mustafa Deploying For CI-CD
on: [push]
jobs:
  MJDeplyPiP: 
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      # - name: Integration-Tests
      #   run: |
      #     cd ./MobileApp/TestsRUS/
      #     # docker run --rm  -v "$(pwd):/app" -w /app/MobileApp/TestsRUS -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet test
      #     dotnet test
      # - name: Unit-Tests
      #   run: |
      #     cd ./MobileApp/UnitTestsRUs/
      #     # docker run --rm  -v "$(pwd):/app" -w /app/MobileApp/UnitTestsRUs -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet test
      #     dotnet test
      # - name: linting
      #   run: |
      #     cd ./MobileApp/
      #     docker run --rm -v "$(pwd):/app" -w /app -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet format --verify-no-changes --severity warn
      # - name: warnining
      #   run: |
      #     cd ./MobileApp/
      #     docker run --rm -v "$(pwd):/app" -w /app/ -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet build
      # - name: deploying
      #   run: |
      #     cd ./MobileApp/MustafasDockerFile
      #     docker compose down
      #     docker compose up --build -d

      - name: deploy
        run: |
          cd ./MobileApp
          docker build -t 144.17.92.12:5000/mustafa/blazor-web:1 .
          docker push 144.17.92.12:5000/mustafa/blazor-web:1
          kubectl delete configmap -n mustafa blazor-web-postgres-init
          kubectl -n mustafa create configmap blazor-web-postgres-init --from-file=init.sql
          
          kubectl apply -f kube/

      # 

      - name: "Notifies Teams Channel"
        uses: dchourasia/ms-teams-notification@1.0  #that is a git lib for templete that I saw in Carlose and used 
        if: always()
        with:
            github-token: ${{ github.token }}
            webhook-uri: ${{ secrets.MUSTAFAHOC }}

# 