name: Mustafa Deploying For CI-CD
on: [push]
jobs:
  MJDeplyPiP: 
    runs-on: self-hosted
    steps:
      - name: "alex-office2"
        run: |
            rm -rf ./GrafanaOpenTelemetryPluralsight1
            git clone "https://${{secrets.CICD}}@github.com/MJebran/GrafanaOpenTelemetryPluralsight1"
            # cd to gitub   
            cd ./GrafanaOpenTelemetryPluralsight1/MobileApp/MustafasDockerFile
            docker compose up --build -d

      - name: Integration-Tests
        run: |
          cd ./GrafanaOpenTelemetryPluralsight1/MobileApp/TestsRUS/
          # docker run --rm  -v "$(pwd):/app" -w /app/MobileApp/TestsRUS -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet test
          dotnet test
          
      - name: Unit-Tests
        run: |
          cd ./GrafanaOpenTelemetryPluralsight1/MobileApp/UnitTestsRUs/
          # docker run --rm  -v "$(pwd):/app" -w /app/MobileApp/UnitTestsRUs -e DOTNET_CLI_HOME="/tmp/dotnet" --user $(id -u):$(id -g) mcr.microsoft.com/dotnet/sdk:8.0 dotnet test
      
      


      #       # docker compose down -v 
      # - uses: actions/checkout@master
            
      # - name: Check Compose Outcome
      #   if: ${{ success() }}
      #   run: |
      #       echo "Docker Compose succeeded."
            
      # - name: letMicrosoft know Teams
      #   uses: skitionek/notify-microsoft-teams@master
      #   if: always()
      #   with:
      #       webhook_url: ${{ secrets.CICD }}