name: pull request environmnet
on: 
    pull_request:
        types: [opened, reopened]
jobs: 
    deploy-to-kubernetes:
        runs-on: self-hosted
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: deploy to kubernetes
              run: |
                export PULL_REQUEST_ID=${{ github.event.pull_request.number }}
                echo $PULL_REQUEST_ID
                export RUN_SALT="pr-${PULL_REQUEST_ID}-${GITHUB_RUN_ID}"
                export NAMESPACE="mustafa-pr-$PULL_REQUEST_ID"
                
                kubectl create namespace mustafa-pr-$PULL_REQUEST_ID || true

                cd ./MobileApp/kube-configs
                kubectl -n mustafa-pr-$PULL_REQUEST_ID delete configmap blazor-web-postgres-init || true
                kubectl -n mustafa-pr-$PULL_REQUEST_ID create configmap blazor-web-postgres-init --from-file=init.sql

                docker build -t 144.17.92.12:5000/mustafa/blazor-web:$RUN_SALT
                docker push 144.17.92.12:5000/mustafa/blazor-web:$RUN_SALT  
                
                for file in  ./kube-pr/*; do 
                    echo "Applying $file"
                    cat $file | envsubst | kubectl apply -f -
                done
